Kan 34 implement station production view
SimonSays-PM4/simon-says pull request #99
Opened 2024-05-12 17:47 UTC by M-Weirauch

## Overview

Please provide a brief description of what this pull request aims to achieve.
Closes KAN-34
Closes KAN-55
Closes KAN-127
Closes KAN-131

### Related Jira Story

Link to the Jira Story and any relevant Sub-Tasks that are addressed by this pull request.

### Backend Changes

- Summary of backend changes here

### Frontend Changes

- Summary of frontend changes here

### Printer Changes

- Summary of frontend changes here

## Definition of Done

- [ ] The feature must be fully tested and all specified requirements being met as outlined in the feature description.
- [ ] Unit and integrations test must be written for any business logic.
- [ ] Sufficient negative tests must be included to assess the robustness and error handling capabilities of the code.
- [ ] The pull request must be reviewed and approved by at least one codeowner of the modified files.
- [ ] All pipelines on the pull request succeed.
- [ ] Refactoring on the code has taken place.

## Screenshots

Include any relevant screenshots that will help in the review of this pull request.

## Additional Notes

Add any other notes about the pull request here, including any discussions, considerations, or dependencies.

---

Please review the above changes. Upon approval, please squash the commits following the guidelines before merging to the main branch.

2024-05-13 11:04 UTC, koller-patrick approved these changes

2024-05-13 18:22 UTC, larawaespe requested changes

2024-05-13 18:22 UTC, larawaespe commented on backend/src/main/kotlin/ch/zhaw/pm4/simonsays/service/StationService.kt
> +    private fun makeStationReadyForUpdate(station: StationCreateUpdateDTO, eventId: Long, ingredients: List<Ingredient>): Station {
please move the private fun to the end of the file

2024-05-13 19:55 UTC, Mcluky requested changes

2024-05-13 19:55 UTC, Mcluky commented on backend/src/main/resources/application-dev.yaml
> +  frontend-origins:
can you update this for the other yaml files as well?

2024-05-13 19:58 UTC, Mcluky commented on backend/src/main/resources/application-dev.yaml
>    url: "http://localhost:3000"
was this not also used just for cors? Can we not remove this when we now have the other configuration field for the frontend origins?

2024-05-14 16:50 UTC, M-Weirauch commented on backend/src/main/resources/application-dev.yaml
>    url: "http://localhost:3000"
@Mcluky I cleaned up the config files a bit, can you check to makre sure I didn't break anything?

2024-05-14 17:10 UTC, larawaespe approved these changes

2024-05-14 17:48 UTC, Mcluky approved these changes

2024-05-14 17:49 UTC, merged